description: "Nạp Thẻ Ngay Tại Đây"
reward: "10k = 10Coin\n20k = 20Coin\n30k = 30Coin\n50k = 50Coin\n100k = 100Coin\n200k = 200Coin\n300k = 300Coin\n500k = 500Coin"
rate: 1000 #1000 Vnđ = 1 Coin
bonus: 1 #event các sự kiện nạp thẻ x2,3,4
broadcastsuccess: "Cảm Ơn Bạn Đã Ủng Hộ Server, {PLAYER}"
#Để "" Nếu Bạn Muốn Tắt Commands Khi Nạp Thành Công
#{PLAYER} Lấy Tên Của Player
#{AMOUNT} Số Phần Thưởng Nhận Được
#Ví Dụ: givemoney {PLAYER} {AMOUNT}
#Nêú Bạn Chỉnh economy thành true vui lòng để chỗ commands này thành ""
commands: "givemoney {PLAYER} {AMOUNT}"

#Tôi khuyên chân thành bạn nên sử dụng tính năng này thay cho commands. Vì commands sẽ bị lỗi khi player có tên dấu cách
#Support EconomyAPI, CoinAPI, PointAPI, DFRuby
#Nêú Bạn Sử Dụng Tiền Tệ Như BedrockEconomy, Capital Thì Vui Lòng Tự Chỉnh Trong NapThe.php
economy: false
economy.use: "DFRuby"

#Plugin Chỉ Hỗ Trợ Website Vuathe.Net
#id (partner_id) và key (partner_key) lấy tại web vuathe.net vào danh mục rồi kết nối api nhập tên ( gì cũng đc ) , Hình Thức (Kiểu) Post, callback bạn ghi domain hoặc ip của server bạn
id: "8955440592"
key: "5825a2f49af984c06f3c1015fba5c5ad"
